name: zaitun_ministry
description: Zaitun Ministry Mobile Application.
version: 1.0.1+2

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  audio_service: ^0.7.2
  cupertino_icons: ^0.1.2
  flutter_tts: ^0.9.1
  google_maps_flutter: ^0.5.25+3
  http: ^0.12.0+4
  just_audio: ^0.1.5
  package_info: ^0.4.0+17
  upgrader: ^0.10.4
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/backgrounds/
   - images/icons/
   - images/logos/

  fonts: 
    - family: Acme
      fonts:
        - asset: fonts/Acme-Regular.ttf
    - family: GochiHand
      fonts:
        - asset: fonts/GochiHand-Regular.ttf
    - family: IndieFlower
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf
    - family: Kalam
      fonts:
        - asset: fonts/Kalam-Regular.ttf
    - family: KaushanScript
      fonts:
        - asset: fonts/KaushanScript-Regular.ttf
    - family: PressStart2P
      fonts:
        - asset: fonts/PressStart2P-Regular.ttf